-- PUBLIC.DEVICE definition

-- Drop table

-- DROP TABLE PUBLIC.DEVICE;

CREATE TABLE PUBLIC.DEVICE (
	MODEL VARCHAR_IGNORECASE(255) NOT NULL,
	MANUFACTURER VARCHAR_IGNORECASE(255) NOT NULL,
	ATYPE VARCHAR_IGNORECASE(255) NOT NULL,
	ID_MODEL INTEGER NOT NULL AUTO_INCREMENT,
	CONSTRAINT DEVICE_PK PRIMARY KEY (ID_MODEL)
);
CREATE UNIQUE INDEX PRIMARY_KEY_7 ON PUBLIC.DEVICE (ID_MODEL);

-- PUBLIC.STOCKROOM definition

CREATE TABLE PUBLIC.STOCKROOM (
	ID_STOCKROOM INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR_IGNORECASE(255) NOT NULL,
	ADDRESS VARCHAR_IGNORECASE(255) NOT NULL,
	MANAGER VARCHAR_IGNORECASE(255) NOT NULL,
	COUNTRY VARCHAR_IGNORECASE(255) NOT NULL,
	STATE VARCHAR_IGNORECASE(255) NOT NULL,
	NEIGHTBORHOOD VARCHAR_IGNORECASE(255) NOT NULL,
	CONSTRAINT STOCKROOM_PK PRIMARY KEY (ID_STOCKROOM)
);

-- PUBLIC.PERSON definition

CREATE TABLE PUBLIC.PERSON (
	NAME VARCHAR_IGNORECASE(255) NOT NULL,
	LAST_NAME VARCHAR_IGNORECASE(255) NOT NULL,
	MOBILE INTEGER NOT NULL,
	DNI INTEGER NOT NULL,
	PASSWORD VARCHAR_IGNORECASE(255) NOT NULL,
	CONSTRAINT PERSON_PK PRIMARY KEY (DNI)
);

-- PUBLIC.DEVICEINSTOCK definition

CREATE TABLE PUBLIC.DEVICEINSTOCK (
	ID_DEVICEINSTOCK INTEGER NOT NULL AUTO_INCREMENT,
	QUANTITY INTEGER NOT NULL,
	STOCKROOM VARCHAR_IGNORECASE(32) NOT NULL,
	DEVICE VARCHAR_IGNORECASE(32) NOT NULL,
	CONSTRAINT DEVICEINSTOCK_PK PRIMARY KEY (ID_DEVICEINSTOCK)
);